### ISSUE TITLE
About folder structure

### ISSUE THREAD

**Issue by hchouhan** [markjaquith/feedback#16]
Hello Mark,

After going through your development folder structure, i.e. using WordPress as submodule, I am trying to replicate the structure. It works locally great. But on my shared hosting I run into issue mainly because until now, I used to keep 'wp-config.php' outside the public_html folder. This results in the file not being accessible to WordPress.

Is there a way to keep the config file outside the working folder and yet get WordPress to work if its setup as below ?

```
root (mywebsite.com)
- wp.config.php
- public_html/
-- wordpress/ (contains all WP files except wp-content folder)
-- wp-content/
-- uploads
```

Secondly, when you are using WordPress as a submodule, in the settings field, is the value of "WordPress Address (URL)" set to yourwebsite.com or yourwebsite.com/wp/ ?

I apologize beforehand if this might be confusing and I am trying to do something beyond my skill level.

**Comment by markjaquith** [comment]
WordPress only looks "up" one level. So if you want to put your actual config file up two levels, you can just make a symlink so that it resolves one level up.

When you're using WordPress in a subdirectory (whether it is a Git submodule doesn't matter), your "WordPress Address" should be the public URL to that subdirectory. So yes, `http://example.com/wp`.

**Comment by hchouhan** [comment]
Thanks @markjaquith. Appreciate you taking time to reply.

**Comment by bueltge** [comment]
Additional a small hint to a discussion about wp-config.php in a deeper level - http://wordpress.stackexchange.com/questions/58391/is-moving-wp-config-outside-the-web-root-really-beneficial
