### ISSUE TITLE
How to work with WP skeleton and send pull requests (should you?)

### ISSUE THREAD

**Issue by kiwitotoro** [markjaquith/feedback#21]
I asked this on Stackoverflow before finding this Q&A 
http://stackoverflow.com/questions/23557892/update-wordpress-when-using-github-wordpress-skeleton
I was trying to improve my usage of Wordpress by learning how to automate processes and found many tutorials using WP-Skeleton but I hit a snag with not knowing how to handle updates to Wordpress. It said in the readme to send you a pull request but I had pulled your code to my local computer. Also I assume if I customise my code and add themes etc you are not going to want to pull that into your code so should I make my own public copy of your repo and clone that, then if Wordpress updates i should update the original copy and send you a pull request?

Sorry if this all sounds simple but I am confused about what is best to do.

I also noticed that the Wordpress repo you reference is out of date (though it says it updates every 20 min?) so if that updates would I just be able to pull the changes?

**Comment by markjaquith** [comment]
You can just open an issue reminding me to update the core repo (honestly, I should automate that).

For your personal sites, which have likely wildly diverged, the update process is as follows:

``` bash
cd wp
git fetch
git fetch --tags
git checkout 3.9.1
cd ../
git add wp
git commit -m 'Update to WordPress 3.9.1'
git push origin master
```

---

Let me break that down:
1. `cd wp` — move into the WordPress submodule directory.
2. `git fetch` — Pull down the latest changes from tracked branches.
3. `git fetch --tags` — Pull down the new tags. You do steps 2 and 3 in this order because otherwise you might have a tag that points to a commit that you don't yet have in your repo.
4. `git checkout 3.9.1` — Checkout the 3.9.1 tag.
5. `cd ../` — Move back into the main directory. At this point, the `wp` subdirectory will show as having changes, since it points to a different commit.
6. `git add wp` — Tell your main repo to stage the WordPress submodule repointing.
7. `git commit -m 'Update to WordPress 3.9.1'` — Commit that change
8. `git push origin master` — Push your master branch (change if using a different branch) up to your origin remote (change if using a different remote).

---

You probably noticed that there is only one variable here — the version number. So You could wrap that up into a bash script that you check into your root directory. And then you could just do something like: `./wpupdate 3.9.1`. Or you could write a script that iterates through a bunch of WordPress site checkouts and does this process on each of them (I've done exactly that).

**Comment by danielbachhuber** [comment]
Or, better than `git fetch --tags` (imo) is `git checkout 3.9-branch`. Committing a tag hash has the nasty habit of kicking you in the future — you have to remember to do `git fetch --tags` each time you deploy, etc.
