### ISSUE TITLE
How do I get paid like you do? 

### ISSUE THREAD

**Issue by arbet** [markjaquith/feedback#38]
Mark,

Your stated hourly rate is $350/hour, while mine sits at $45. Most of my prospects aren't willing to pay more. What should I do in order to raise my hourly rate? You've already traveled that path, so I would love to hear from you what works.

**Comment by hiddenpearls** [comment]
Mark,

This is an important question and I want to know the answer :)

Thanks

On Wed, Aug 20, 2014 at 5:20 PM, arbet notifications@github.com wrote:

> Mark,
> 
> Your stated hourly rate is $350/hour, while mine sits at $45. Most of my
> prospects aren't willing to pay more. What should I do in order to raise my
> hourly rate? You've already traveled that path, so I would love to hear
> from you what works.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markjaquith/feedback/issues/38.

## 

Muhammad Adnan
twitter: @hiddenpearls http://www.twitter.com/hiddenpearls
I blog too do u know ?  adnan.pk http://www.adnan.pk/
Failure takes you higher than success ..!

http://www.youtube.com/watch?v=HbEpeiYdzh8

**Comment by MickeyKay** [comment]
@arbet, have you actually tried raising your rates? What is stopping you from charging, say $55/hr? $65/hr? $100/hr?

I ask because - while skill is undeniably a large factor in calculating one's rate - I often find that the biggest obstacle (for myself as well) is fear that my rate will seem too high to prospective clients.

What might it look like to just up your rate for your next client? When was the last time you did up your rate?

Lastly, there are loads of articles out there on this topic (because it's such a common challenge, I think). Chris Lema is one author who has written quite a bit on the subject, and he (like Mark) is able to charge a pretty awesome rate in my judgement. Here's one article to get you started if you haven't seen it already: http://chrislema.com/pricing-challenges-raising-rates/

Particularly, I think this quote sums up a common (and successful) approach:

> Start by defining your hourly rate. Then, when you notice that everyone is accepting your hourly rate without issue, raise it. Keep raising it until you notice some percent of people are walking away. At that point leave it there until everyone starts accepting your rate again. 

Hope this helps! Know too that I've raised my rates several times in the recent past, and this is still an ongoing challenge :)

**Comment by arbet** [comment]
@MickeyKay , I've tried raising my rates, but I find that if I go above $45/hour, I get much lesser projects. I find most of my clients on oDesk and eLance, and the clients on these platforms aren't used to paying more than that, since there is lots of competition there. I'm also on the other side of the globe, and local clients don't pay much, which is why face to face is not an option for me. 

My problem lies in generating high quality leads. I'm not sure what to do: Would contributing to open source bring me better clients? Should I write a book? Should I blog more?  

I'm trying to understand what would bring me clients who are willing to pay more.

**Comment by tnorthcutt** [comment]
> Should I blog more?

Almost certainly yes. Build expertise (learn things), demonstrate that expertise (write about those things), then apply that expertise in valuable ways to _people who value that expertise_. Hint: those people are almost universally _not_ looking for help on oDesk, et al.

**Comment by markjaquith** [comment]
I wrote about pricing a bit in the e-book available here: http://codepoet.com/2012/05/11/getting-pricing-right/

If raising your prices causes you to get less work, then you have to work on raising your skills and reputation. Releasing free plugins and themes is a great way to advertise your skills. Blogging is a great way to advertise your knowledge.

Another thing to do is to pick something that is "new" in the WordPress scene. An example right now is configuring servers with HHVM for high performance. Play around with that. Learn some things. Blog about it. Before you know it, you'll be one of the go-to people for that thing, and you'll be able to charge higher rates.

Find a niche that is underserved. Say... custom EDD add-ons. Learn it, get good at it, and then advertise yourself as an expert in that area.

**Comment by davidfavor** [comment]
Mark's advice is sound.

My pricing is a bit different.

$100/hour for all work.

And I drive new clients to hosting with me.

As trying to tune a CentOS + CPanel system running the hacked up Apache ITK MPM is impossible. The testing I've done shows most versions of ITK reduce site speed by 95%.

So your pricing depends on your model. I typically only take on new clients, where first work is migrating all their sites to one of my servers, so they pay monthly hosting ($100-$1000+/month).

I prefer monthly continuity (hosting) over ad-hoc hourly work.

That's just me.
