### ISSUE TITLE
Are Grandchild Themes a good idea or not?

### ISSUE THREAD

**Issue by trishacupra** [markjaquith/feedback#4]
I'm wondering what the best practice is for customizing a child theme. Does creating a grandchild theme slow a site down too much? Should child themes be created and distributed with the expectation that nobody will want to customize them and then be concerned about updates wiping out custom css and functions?

Thanks!

**Comment by markjaquith** [comment]
So, I have a bit of a disagreement with how some themes (like StudioPress themes) are sold. I don't think it's such a great idea to sell child themes. I see child themes as a way for end users to customize a theme without touching the original theme. Grandchild themes aren't supported in WordPress core.

I believe the StudioPress line on this question is that they update their child themes very infrequently, so it's not a problem that comes up a lot.

If you're interested in a better and more flexible system for WordPress core, check out this ticket: https://core.trac.wordpress.org/ticket/22355

There isn't really a good answer now. I would recommend that people modifying child themes do so in a version control system (or at least keep a copy of the original unmodified one to compare against), so that if there are upstream updates, they'll know what code is custom.
