### ISSUE TITLE
How did this AMA approach work out for you?

### ISSUE THREAD

**Issue by Rarst** [markjaquith/feedback#76]
I had been thinking about trying AMA as a channel for people to approach me with questions (in a more welcoming form and such).

How did having this AMA work out for you in general and using GitHub as a platform for it specifically? Do you feel it had been valuable to you, people asking, and larger community around?

**Comment by markjaquith** [comment]
I found it valuable. With my answers being public, I felt like my answers were more meaningful, because they wouldn't just get lost in one person's inbox.

I'm a big fan of GitHub's issues software, and found that this was a perfectly fine use of it.

I kinda fell away from it, but not for any real reason that GitHub notification bloat (problems with my configuration of notifications, not GitHub's problem). I should remember to steer people here when I get asked a good question that would be valuable to more than the one person who asked.
